### ISSUE TITLE
usage of require limits file size of json

### ISSUE THREAD

**Issue by schwer** [firebase/firebase-import#17]
If you use the "require" to read the .json file, it will limit the size of the json file. A streamed json parser, like JSONStream might improve the capability to read large files. Granted, this approach would not solve the memory usage issue for those files once they are memory resident, but it would give a little more headroom.

**Comment by katowulf** [comment]
See also https://github.com/firebase/firebase-streaming-import

**Comment by schwer** [comment]
I don't have a suitable python environment on the machine that I'm using to run firebase. I've forked the repo and plan on sending a PR with what I have in mind.

**Comment by schwer** [comment]
I think this is resolved via https://github.com/firebase/firebase-import/pull/18. Another pull request is needed to update the documentation to reflect that the file-size limit is no longer 250mb, but is roughly the amount of available memory on the machine.
