### ISSUE TITLE
Despite setting --path to /, it points to /C%3A/Program%20Files/Git.

### ISSUE THREAD

**Issue by PAK90** [firebase/firebase-import#19]
This is my input and what I get out:

```
$ firebase-import --database_url https://projectName.firebaseio.com --path / --json allTest.json

The 'serviceAccount' property specified in the first argument to initializeApp() is deprecated and will be removed in the next major version. You should instead use the 'firebase-admin' package. See https://firebase.google.com/docs/admin/setup for details on how to get started.
All data at https://projectName.firebaseio.com/C%3A/Program%20Files/Git will be overwritten.
Press <enter> to proceed, Ctrl-C to abort.
```

I hit enter, it proceeds apparently normally, but when I check my database none of the new data in my json file has been uploaded; my old data is untouched. Why's it adding that extra ProgramFiles/Git to the path?

**Comment by mikelehen** [comment]
Is this bash on Windows or something?  Can you try using a normal command-prompt?  It seems like something is transforming "--path /" into "--path C%3A/Program%20Files/Git"

**Comment by PAK90** [comment]
Ah, yeah. I was using the git bash command prompt on Windows, clearly that adds something extra. Using it on the normal `cmd` with the exact same command overwrites the root like I want it to; it works perfectly. Thanks :)
