### ISSUE TITLE
publish last version on npm

### ISSUE THREAD

**Issue by fpereira1** [firebase/firebase-import#21]
Hi,

It looks like the `master`  branch has a `package.json` file that has a version `0.0.0` https://github.com/firebase/firebase-import/blob/master/package.json#L4

I think this needs to be `2.0.1` and the package needs to be published on npm.

Currently if you install `npm install -g firebase-import` you don't get the latest version that is in `master`

**Comment by fpereira1** [comment]
Also, was there a reason to remove the `bin` folder from the repository in this commit: https://github.com/firebase/firebase-import/commit/4888711cb16e8c342b36e30de710df997543266b

it doesn't seem like the npm script `npm run build` runs at pre-release, so it would make sense to me to keep the `bin` folder in the repository.

**Comment by mikelehen** [comment]
Sorry, this is all part of our automated release process...  We have a script that checks in the bin output, sets the version number, tags the release, pushes it to npm, and then reverts the changes it checked in.

So I just need to get around to kicking off a release.  This isn't super hard, but I need to do a bit of manual testing first to make sure we're in a good state, and I'm swamped at the moment.  So I may not get to it immediately.  I apologize for the inconvenience.

**Comment by fpereira1** [comment]
All good thanks @mikelehen - I will close this issue 😄 👍
