### ISSUE TITLE
sync stops working when path is blown away with firebase-import

### ISSUE THREAD

**Issue by leblancmeneses** [firebase/firebase-import#23]
I'm using firebase-import here:
https://www.dnwdebt.com/app#/demo/2500

To refresh the demo data every 30 minutes.

I notice that most times the sync stops when data is refreshed from json backups.
It requires the user to refresh the page.

IMHO this is a bug with firebase. $ref points to a path and doesn't receive any events that data was recreated and the client should be resynced.   It seems the delete events occurred but not the create.

**Comment by mikelehen** [comment]
Hrm.  I don't think this is an issue with firebase-import as it's simply doing a normal write to your Database.  Perhaps you can isolate what code in dnwdebt.com is failing when the import happens and then log an issue (against  whatever library you're using or with Firebase Support  https://firebase.google.com/support/).  Good luck!
