### ISSUE TITLE
Firebase import

### ISSUE THREAD

**Issue by amandaalonzo** [firebase/firebase-import#28]

**Comment by amandaalonzo** [comment]
[pipelineLog-1.txt](https://github.com/firebase/firebase-import/files/1294973/pipelineLog-1.txt)



[Cloud_Marketplace__Management_Service_Data_Sheet (1).pdf](https://github.com/firebase/firebase-import/files/1294964/Cloud_Marketplace__Management_Service_Data_Sheet.1.pdf)



![google-apps-section-3](https://user-images.githubusercontent.com/28499286/30311886-8a7a0be8-9754-11e7-93c7-e1202d8d3354.jpg)
[#``](
![team-settings-teamsid](https://user-images.githubusercontent.com/28499286/30311871-7cbb7168-9754-11e7-8fe0-64aa0e556a53.png)
)


O

**Comment by katowulf** [comment]
No context here. Closing.
