### ISSUE TITLE
How to Generate PushKeys for data in Json file

### ISSUE THREAD

**Issue by afficionaddo** [firebase/firebase-import#32]
I have json data as follows:
I want this to add under a node like /courses in database:

{
	"description" : "test course",
	"title" : "New Course Title",
	"url" : "https://courseurl.com" 
}

But on import, It does not generate PushKeys like it does when we invoke .push({obj}) method of Firebase.
SO how to generate PushKey on import for data?

**Comment by mikelehen** [comment]
firebase-import is meant for importing data verbatim. It doesn't generate keys for you.  You'll need to use the client SDK so you can use .push(), or the REST API (and use POST): https://firebase.google.com/docs/reference/rest/database/#section-post

Sorry!
