### ISSUE TITLE
Please update Readme: firebase-streaming-import is no longer useable

### ISSUE THREAD

**Issue by philshem** [firebase/firebase-import#35]
README.md in this repository points to [firebase-streaming-import ](https://github.com/firebase/firebase-streaming-import) for JSON files larger than 250MB.

After extensive testing with that package, and from reading the issues and comments, and also noticing the last commit was more than 4 years ago, I would request that the link from this package to that one would be removed - due to that package being not supported and in-effect "broken".

(according to the [comments](https://github.com/firebase/firebase-import/issues/29#issuecomment-371900390) in a similar issue, it seems streaming support is ready in firebase-import but needs to be pushed to npm, although with 2.1.0 I'm not able to load 1gb JSON)

**Comment by mikelehen** [comment]
Good point.  PR welcome.
