### ISSUE TITLE
Can't handle large imports

### ISSUE THREAD

**Issue by hijonathan** [firebase/firebase-import#4]
Throws `FATAL ERROR: CALL_AND_RETRY_0 Allocation failed - process out of memory` for large files (greater than `256MB`).

**Comment by mikelehen** [comment]
Unfortunately, firebase-import tries to load the whole JSON file by doing a require('foo.json') and even on systems with large amounts of memory, node has fairly restrictive memory limits.  You could try doing:

    node --max_old_space_size=8192 `which firebase-import` -f <FIREBASE URL> -j <JSON FILE>

But I think node can only use 1G or 1.7G depending on if you're on 32-bit or 64-bit.

The right fix is to rework firebase-import to use a streaming approach, but I'm not sure how much work that'll be.

Sorry!
