### ISSUE TITLE
Importing firebase user accounts

### ISSUE THREAD

**Issue by 111studio** [firebase/firebase-import#5]
Hello,

For an app I'm building, I need to create close to 50k user accounts on my firebase. I'm using the email & password Authentication.

I have the list of user accounts in json format ready with a random password generated.

My question is, can I use this tool to import my user accounts ?

Kind regards,

Florian

**Comment by mikelehen** [comment]
Hi Florian, this script is for importing firebase data not firebase users. However you could probably build a similar script pretty easily for importing firebase users that just calls our createUser method repeatedly.

**Comment by 111studio** [comment]
Got it thanks, will do as you suggested. And probably link back the repo I created in here.

Florian
